FROM renra/ruby-postgres:ruby2.3.0-postgres9.4.12

RUN apt-get -qqy update && apt-get install -qqy \
        apt-transport-https \
        lsb-release

RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" > /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update && \
    apt-get install -y google-cloud-sdk && \
    apt-get install -y google-cloud-sdk-pubsub-emulator
